baseURL = "https://competent-carson-57dae4.netlify.app"
languageCode = "en-us"
title = "VARS2021"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Milad Kazemi"
    description = "2021 CPS-IoT Week Workshop: Verification of Autonomous & Robotic Systems ( VARS)"
    Milad Kazemi
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/organizers/"
    name = "Organizers"
    weight = 3

[[menu.main]]
    url = "/speakers/"
    name = "Speakers"
    weight = 4 

[[menu.main]]
    url = "/pc/"
    name = "Program Comittee"
    weight = 5 

[[menu.main]]
    url = "/si/"
    name = "Submission Information"
    weight = 6 

[[menu.main]]
    url = "/id/"
    name = "Important Dates"
    weight = 7 
   
[[menu.main]]
    url = "/contactus/"
    name = "Contact us"
    weight = 8    

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.
